owner_email    = "youremail@company.com"
purpose        = "WhyAreYouCreatingThisInfrastructure"
subscription   = "your-azure-subscription"
region         = "azure-region"
env_name       = "EnvironmentDisplayName"
cluster_name   = "ClusterDisplayName"
network_name   = "NetworkDisplayName"

resource_group = "AzureResourceGroup"
vnet_name      = "AzureVNET"
